### ISSUE TITLE
data sprint 2 of Henry Ford Health System

### ISSUE THREAD

**Issue by yonghu1** [cumc-dbmi/pmi_sprint_reporter#11]
Hi,
On the submission list of data sprint share by Karthia, Henry Ford Health System's files name seems not accurate. We uploaded six files for data sprint 0 and five files of data sprint 2 (person, visit, condition, procedure and measurement ) .  We are working on the drug exposure. Would you please check the receiving files and let us know if we need to re-submit any file. 

The file names for data sprint 0 start with "TACHI_HFHS", but the data sprint 2 start with "TACH_HFHS". 

Thanks,
Yong

**Comment by mark-velez** [comment]
@yonghu1 we will update [hpo.csv](https://github.com/cumc-dbmi/pmi_sprint_reporter/blob/master/docs/_data/hpo.csv#L21) and re-run like you suggested. I will follow-up here afterward.
