### ISSUE TITLE
Streamline process from file transfer to refresh

### ISSUE THREAD

**Issue by mark-velez** [cumc-dbmi/pmi_sprint_reporter#13]
By automating download from secure transfer. This would reduce lag as mentioned in #11 so the report is as up to date as possible.

**Comment by mark-velez** [comment]
@cukarthik Please pull experimental branch [download](https://github.com/cumc-dbmi/pmi_sprint_reporter/tree/download) and follow these steps:
 * set `settings.csv_dir` to our shared folder
 * execute the `download` module

This *should* reload the `pmi_sprint_reporter_downloads` table and then download and save the latest version of each submission to the shared folder. If it works, we'll be very close to having a fully automated process. We would just have to schedule a job that would execute `download` and then `reporter`.

**Comment by mark-velez** [comment]
@cukarthik It looks like authorization is failing. The files in the share are all error responses in HTML from accellion. Can you confirm that `settings.accellion` has `username` set to your e-mail address and has the correct password?

**Comment by mark-velez** [comment]
@cukarthik I think 8b3c16f may fix the problem. I've also increased the column sizes on the table `pmi_sprint_download` and dropped it on dev. Please let me know when you've had a chance to pull and run it again.

**Comment by cukarthik** [comment]
@mark-velez I did and increased the column size more and now it works. I'm working on automating the pipeline, with the job running every 3 hrs.

**Comment by mark-velez** [comment]
I'm closing this issue since we have automated download and have a scheduled job. Note to self: have more concrete issue descriptions than this one.
