### ISSUE TITLE
ORA-00932: inconsistent datatypes: expected NUMBER got CLOB

### ISSUE THREAD

**Issue by johntmilnes** [cumc-dbmi/pmi_sprint_reporter#15]
Hi - I'm having problems getting my condition_occurrence ( and other tables) loaded using the Sprint Reporter tool. The issue is with the date format on columns like: condition_start_date. 

I'll attach a sample of the csv layout and the sprint_reporter_log table records.
Can you confirm the required date format for each of the 4 date columns in the condition_occurrence table?
[reporter_date_format_layout.txt](https://github.com/cumc-dbmi/pmi_sprint_reporter/files/767573/reporter_date_format_layout.txt)

**Comment by mark-velez** [comment]
Thank you for reporting this. We want to maximize compatibility with database engines that sqlalchemy supports, but have only tested on MS SQL Server and sqlite (e.g. `conn_str='sqlite:///pmi_sprint_2.db'`). The latter to a lesser extent. I can't guarantee we'll reach feature-complete on all platforms, but Oracle would probably be third on the list.

Ok, that being said, I just took the first step to fixing this and replicated the bug on Oracle. I gave it a file which passed on mssql and sqlite (e.g. `condition_occurrence` from `pitt`) and got the same error you mentioned. On Oracle it appears that sqlalchemy generates `DATE`s where a type which includes the time was intended (screenshot below). I'm personally not familiar with how Oracle handles `DATETIME`. @cukarthik @johntmilnes would you have any insight here?

![image](https://cloud.githubusercontent.com/assets/8049605/22847994/20ecd526-efbf-11e6-8591-55f4c9cd461d.png)

**Comment by johntmilnes** [comment]
Hi Mark- 
     That's right.  Oracle's Date format hold times down to a sec and that's the datatype used in the omop tables. To get the data in you typically use the to_date function with the correct format mask for your input string.
How sqlAlchemy structures things is unknown to me but some straight sql might get you started:

################
  CREATE TABLE DATE_TESTING (
          START_DATE	DATE,
          START_DATETIME	TIMESTAMP) ;

--Default date format
insert into DATE_TESTING (START_DATE) values ("2015-01-01");
--Sample to_date w format mask
insert into DATE_TESTING (START_DATE) values (to_date('11-FEB-17 10.19.58','YYYY-MM-DD HH24:MI:SS'));
-- Sample substring-ing 
 insert into DATE_TESTING (START_DATETIME) values  (TO_DATE(substr('2015-01-01T00:00:00-05:00',1,10)||' '||substr('2015-01-01T00:00:00-05:00',12,8), 'YYYY-MM-DD HH24:MI:SS') );
-- Extacting  just HH24:MI:SS
select substr('2015-01-01T00:00:00-05:00',12,8) from dual;

http://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements004.htm#i34924 
http://docs.oracle.com/cd/B19306_01/server.102/b14200/functions180.htm

-John

**Comment by mark-velez** [comment]
Documenting that the error `(cx_Oracle.DatabaseError) ORA-00932: inconsistent datatypes: expected NUMBER got CLOB` occurs when we do insert [here](https://github.com/cumc-dbmi/pmi_sprint_reporter/blob/220353b87f32fb76ee79801e1827bc42afe5e067/reporter.py#L179) using `pandas.Dataframe.to_sql()`.

In an ideal world we could trust sqlalchemy to abstract away these idiosyncrasies for us, but alas. I found a related (supposedly fixed) [issue](https://bitbucket.org/zzzeek/sqlalchemy/issues/793) which suggests that on oracle, sqlalchemy's `to_date` might yield `CLOB`s.

@johntmilnes in the meantime are you able to run `reporter.py` using a sqlite connection?
