### ISSUE TITLE
Add date of load information to the Sprint Reporter report page

### ISSUE THREAD

**Issue by johntmilnes** [cumc-dbmi/pmi_sprint_reporter#16]
For this page: https://cumc-dbmi.github.io/pmi_sprint_reporter/report.html 

Can you add a date or timestamp that reflects when the data load was run? 

I don't know how you are setting up this process so this might be a simple as a single run date at the top of the page..  but would be very helpful for the sites to know which of their submitted files are being referred to.
Thanks

-John

**Comment by mark-velez** [comment]
Thank you @johntmilnes, that's a great idea. We will think about how to go about it and keep you posted.
