### ISSUE TITLE
CHCI chci_visit_occurrence_datasprint_2.csv missing

### ISSUE THREAD

**Issue by typhilips** [cumc-dbmi/pmi_sprint_reporter#18]
Hi 
I submitted the visit file on 1-15-17 but it is not listed on the report.
Thank you 
Tyler 
[2-14-17 visit file email.pdf](https://github.com/cumc-dbmi/pmi_sprint_reporter/files/774515/2-14-17.visit.file.email.pdf)

**Comment by mark-velez** [comment]
In the screenshot there appears to be a typo (missing 'r'). Unfortunately, the tool is very picky about spelling. It won't process a file that is misnamed; it will just say it couldn't find it. Renaming the file and resubmitting it should correct the issue.

**Comment by typhilips** [comment]
Hi
Thank you
Just resubmitted it with the correct spelling ☺
Tyler
