### ISSUE TITLE
Error converting datatype Varchar to Float on reporter page

### ISSUE THREAD

**Issue by johntmilnes** [cumc-dbmi/pmi_sprint_reporter#19]
Hi-  On our Measurement File for our site I'm seeing: 'Error converting datatype varchar to float Check messages from the SQL server.'  on the reporter page.  Are there further details on this issue? Anything I should check?

Thanks

-John

**Comment by mark-velez** [comment]
Hi @johntmilnes. Were you able to run the tool on oracle? You should see in `pmi_sprint_reporter_log.params` the exact row that had an issue. According to our log, the `range_low` field for `measurement` record with `measurement_id=810228620010012` contains '<' and the tool is unable to interpret this as a `float`.

**Comment by johntmilnes** [comment]
Hi Mark - I now get:
python reporter.py
Traceback (most recent call last):
  File "reporter.py", line 17, in <module>
    from run_config import hpo_ids, use_multi_schemas, engine, datetime_tpe
  File "/home/oracle/PMI/pmi_sprint_reporter/run_config.py", line 29, in <module>
    use_multi_schemas = multi_schema_supported and (len(hpo_ids) > 1 or settings.force_multi_schema)
AttributeError: 'module' object has no attribute 'force_multi_schema'
