### ISSUE TITLE
data sprint 2 upload 

### ISSUE THREAD

**Issue by yonghu1** [cumc-dbmi/pmi_sprint_reporter#20]
Hi,

On the report sheet, only three files have been received. We sent six files. If you need us resend the any of the files, please let me know.

Thanks,
Yong

**Comment by mark-velez** [comment]
Hi @yonghu1. The tool is very particular that files follow the naming convention specified in [file transfer procedures](https://cumc-dbmi.github.io/pmi_sprint_reporter/file_transfer_procedures.html). I see a couple of files are missing '_' before '2'. If you rename and resubmit, this should fix the problem.

**Comment by yonghu1** [comment]
Hi Mark,

I re-submitted the unchecked files. Please let me if there is any question about these data.

Thanks,
Yong
