### ISSUE TITLE
NEC procedure/drug files not showing up

### ISSUE THREAD

**Issue by jklann** [cumc-dbmi/pmi_sprint_reporter#21]
NEC procedure and drug files not showing up in the reporter even though I submitted them. Is possible this is because I prepended the name with nec__ instead of nec_phs_ because I am submitting one test file on behalf of the whole HPO. The DataSprint 2 docs indicated this was an allowed name, but the reporter indicates otherwise.

Is this the problem? Would you like me to reupload?

**Comment by mark-velez** [comment]
Hi @jklann. The reporter requires that the `hpo_id` used be one of those listed in [hpo.csv](https://github.com/cumc-dbmi/pmi_sprint_reporter/blob/master/docs/_data/hpo.csv). @cukarthik please advise and make any necessary changes to the file.

**Comment by cukarthik** [comment]
@jklann we ended up changing the hpo_id based on previous submissions. You'll eventually submit for the entire HPO, right? Do you want it broken down by each site? If so, please re upload; otherwise, we can replace nec_phs and nec_bu with just nec. Let us know which one is preferred.

**Comment by jklann** [comment]
yes, when it's real data it should be separate files.

**Comment by cukarthik** [comment]
Okay. Then please resubmit using nec_phs even though the file is combined. Thanks.

**Comment by mark-velez** [comment]
Appears resolved, closing. @jklann please submit a new issue if necessary.
