### ISSUE TITLE
AttributeError: 'module' object has no attribute 'force_multi_schema'

### ISSUE THREAD

**Issue by johntmilnes** [cumc-dbmi/pmi_sprint_reporter#22]
Runing: python2.7 reporter.py 
now gives:
Traceback (most recent call last):
  File "reporter.py", line 17, in <module>
    from run_config import hpo_ids, use_multi_schemas, engine, datetime_tpe
  File "/home/oracle/PMI/pmi_sprint_reporter/run_config.py", line 29, in <module>
    use_multi_schemas = multi_schema_supported and (len(hpo_ids) > 1 or settings.force_multi_schema)
AttributeError: 'module' object has no attribute 'force_multi_schema'

**Comment by mark-velez** [comment]
@johntmilnes there's a new setting (see [_settings.py](https://github.com/cumc-dbmi/pmi_sprint_reporter/blob/master/_settings.py#L27)), you should stick with the default value `False`. Sorry, I don't have a good way of communicating/documenting when there are new settings.
