### ISSUE TITLE
Upload of 2 new files borked previously uploaded ones

### ISSUE THREAD

**Issue by firaswehbe** [cumc-dbmi/pmi_sprint_reporter#25]
Recently I just submitted two files:

`ipmc_nu_drug_exposure_datasprint_2.csv`  
`ipmc_nu_measurement_datasprint_2.csv`  

All other `ipmc_nu_*` files had already been successfully submitted and had shown as "loaded". Now it looks like they reverted back to not showing as loaded even though no new submissions have been made to replace them.

1. Does this reflect new checks done during loading process?
2. How should we respond to the errors that are now showing when you hover? Should we wait for you to reach out or engage @cukarthik or someone else via email?

**Comment by cukarthik** [comment]
@firaswehbe I see that the files were submitted. We are working on automating the load and validation process which is why you are seeing some issues. Hopefully, we'll have it resolved today or tomorrow. I'll update you when it's resolved.

**Comment by firaswehbe** [comment]
Thanks @cukarthik. We'll keep monitoring. Happy to re-send all 6 files in one batch if that helps.

**Comment by cukarthik** [comment]
I re-ran on our side, but there still seems to be an issue. For some reason we are not picking up the id column even though those columns are not blank in the files you sent. @mark-velez can you verify on your environment using ipmc_nu files?

**Comment by cukarthik** [comment]
@firaswehbe do you mind recreating and submitting your files. I think this is a file coding issue that is causing the submission to fail. I want see if recreating your files removes this issue. Thanks.

**Comment by cukarthik** [comment]
@firaswehbe the quotes in the file are in unicode. Can you export your file as plain ascii? This should solve the problem. Thanks.

**Comment by firaswehbe** [comment]
Resubmitted all 6 files in ASCII encoding. Please let us know. We'll monitor the website.

Aside: I think this is suboptimal on the long run. Non-ASCII characters are unavoidable, may need to enable UTF-8 in our data transmission streams.

**Comment by mark-velez** [comment]
@cukarthik do you know if a [byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8) was causing the problem? If we get enough files with this evil character, we may want to look for and strip it. Then we can fully support UTF-8 like @firaswehbe suggested.

**Comment by cukarthik** [comment]
@mark-velez I was thinking that as well, but I think all the column names are in UTF-8. I'm testing more b/c it could have been confounded with issue #26. I'll have a better idea after 5pm when the next job runs.

**Comment by cukarthik** [comment]
@firaswehbe it seems like we are still having the issue. Just curious, what OS and IDE are you using to export the files?

**Comment by pcn913** [comment]
@cukarthik , I generated these files using Windows 7 and Notepad++

**Comment by cukarthik** [comment]
@pcn913 looks like the three of the files were in ascii and the drug_exposure and measurement files were in UTF-8. Do you mind resubmitting drug_exposure and measurement in ascii format. The other files loaded properly. Thanks.

**Comment by cukarthik** [comment]
@mark-velez you were right. It was a BOM issue. I believe this issue is resolved with my latest commit.

**Comment by firaswehbe** [comment]
This seems to have fixed all but one file (measurement). We manually fixed some column characters and I just re-uploaded. Will monitor and hopefully this will resolve the issue for that file. No need to re-open this ticket. Just FYI for now.
