### ISSUE TITLE
Does this work on Windows Systems?

### ISSUE THREAD

**Issue by phs-billing** [cumc-dbmi/pmi_sprint_reporter#27]
Does anyone know if this works on standard Windows systems with CPython installed? Or is there is more required than that (such as Cygwin)?

Thanks -

Dan McLren, HFHS

**Comment by mark-velez** [comment]
We have tested this on Windows 7 and Mac OS X using Python 2.7. Are you running into any issues in particular?

**Comment by mark-velez** [comment]
@phs-billing I'm closing this since we haven't heard back. Please submit another issue with some specifics if there are problems running this.
