### ISSUE TITLE
SyntaxError: invalid syntax File "reporter.py", line 71

### ISSUE THREAD

**Issue by johntmilnes** [cumc-dbmi/pmi_sprint_reporter#4]
Hi - I hit a problem running the sprint_ reporter tool. I pulled down the latest from git updated the settings.py but when I run reporter.py I get:
 
python reporter.py 
  File "reporter.py", line 71
    Table(table_name, metadata, *columns, schema=schema)
                                               ^
SyntaxError: invalid syntax
 
I'm using Python 2.4.3

I'm not sure what the problem is.

Thanks

-John

**Comment by mark-velez** [comment]
I cannot say for certain that this is the cause, but I recommend using `Python 2.7.*`. Also make sure that you  [install the packages in requirements.txt](https://pip.pypa.io/en/stable/user_guide/#requirements-files). We should have added these notes to the readme (I will do it now). Please try that out and let us know the outcome on here. Thanks @johntmilnes .

**Comment by johntmilnes** [comment]
Thanks Mark- using 2.7 with sqlalchemy and pandas gets me a lot closer

I also had to set these two variables to get sqlalchemy to find an Oracle client:
export ORACLE_HOME=/usr/lib/oracle/10.2.0.5/client64
export LD_LIBRARY_PATH=$ORACLE_HOME/lib

Now I get:
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00942: table or view does not exist
 [SQL: "SELECT 1 FROM information_schema.schemata WHERE schema_name = 'pitt'"]

I have the conn_str property in settings.py as:
oracle://PMI_DATA_SPRINT_REPORTER:redacted@dbmi-db-dev01_server:1521/db_sid

where PMI_DATA_SPRINT_REPORTER is a new empty Oracle schema with create table rights. 
Is that the right starting point or is this tool expecting something else?

-John

**Comment by mark-velez** [comment]
You are indeed getting further. Actually, in your case it shouldn't have to run this check. I just pushed a fix which should address this. Please pull and let me know how it goes.

Oracle has a different notion of "schema" than I'm used to, but judging by the output, it appears that your connection string is ok. The connection succeeded and it was able to issue the command, but in this case Oracle does not seem to follow ANSI SQL convention and provide an object `information_schema.schemata`.

**Comment by johntmilnes** [comment]
OK- Thanks Mark - More progress. With the new check ins I get:

Processing pitt...
File not found
File not found
File not found
File not found
(cx_Oracle.DatabaseError) ORA-00932: inconsistent datatypes: expected NUMBER got CLOB

The file not found lines make sense because we have only Person and Visit files so far.
I see that it created the tables and loaded my 100 patient set but the visit occurrence table is empty so perhaps that's the piece generated the datatype error.  I'll poke around and see if I can confirm that..

-John
